server:
  port: 8022
  servlet:
    context-path: /api/v1

spring:
  application:
    name: payment-service
  cloud:
    zookeeper:
      connect-string: 192.168.47.129:2181,192.168.47.130:2181,192.168.47.131:2181
  #  security:
  #    user:
  #      name: admin
  #      password: admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # CAUTION: useAffectedRows=true is necessary
    url: jdbc:mysql://localhost1:13306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&rewriteBatchedStatements=true&failOverReadOnly=false
    username: root
    password: ENC(Qz2z9xgvc5UxDKzPLEhbsw==)
    hikari:
      max-lifetime: 600000
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.liuwei.learn.payment.entity
# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

swagger:
  enabled: true

