server:
  port: 8888

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/evynlau/SpringCloudLearn.git
          search-paths:
            - SpringCloudLearn
      label: config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka