server:
  port: 9012
spring:
  application:
    name: stream-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.47.129:9092,192.168.47.130:9092,192.168.47.131:9092
          auto-add-partitions: true
          replication-factor: 3
      bindings:
        input:
          destination: streamBindingsDest #默认是output
          content-type: application/json
          binder: kafka
          group: consumerA  #同组消费一次，不同组消费多次 ，设置group后未消费的消息还会被再次消费

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka