server:
  port: 2182
zk:
  url: 192.168.47.129:2181,192.168.47.130:2181,192.168.47.131:2181
  timeout: 1000
spring:
  application:
    name: zookeeper-api
springfox:
  documentation:
    swagger-ui:
      enabled: true