server:
  port: 8012
spring:
  application:
    name: order-service

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    #是否从Eureka服务端抓取已有的注册信息，集群情况下需设置为true配合ribbon做负载
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://learn1.51srm.com:9900/eureka,http://learn2.51srm.com:9901/eureka