server:
  port: 9011
spring:
  application:
    name: stream-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.47.129:9092,192.168.47.130:9092,192.168.47.131:9092
          auto-add-partitions: true
          replication-factor: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka