server:
  port: 8020
  servlet:
    context-path: /api/v1

spring:
  application:
    name: payment-service
#  security:
#    user:
#      name: admin
#      password: admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # CAUTION: useAffectedRows=true is necessary
    url: jdbc:mysql://192.168.2.207:13306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&rewriteBatchedStatements=true&failOverReadOnly=false
    username: root
    password: 123456
    hikari:
      max-lifetime: 600000
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.liuwei.learn.payment.entity

swagger:
  enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    #是否从Eureka服务端抓取已有的注册信息，集群情况下需设置为true配合ribbon做负载
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://learn1.51srm.com:9900/eureka,http://learn2.51srm.com:9901/eureka
