server:
  port: 8020
  servlet:
    context-path: /api/v1

spring:
  application:
    name: payment-service
#  security:
#    user:
#      name: admin
#      password: admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # CAUTION: useAffectedRows=true is necessary
    url: jdbc:mysql://localhost1:13306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&rewriteBatchedStatements=true&failOverReadOnly=false
    username: root
    password: ENC(WH182nMzvpVl54LJMbUeYA==)
    hikari:
      max-lifetime: 600000
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.liuwei.learn.payment.entity

swagger:
  enabled: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

eureka:
  instance:
    hostname: localhost
    #eureka 主机名称
#    instance-id: 51srm
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时剔除
    lease-expiration-duration-in-seconds: 90
    #Eureka客户端向服务端发送心跳时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    #是否从Eureka服务端抓取已有的注册信息，集群情况下需设置为true配合ribbon做负载
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://learn1.51srm.com:9900/eureka,http://learn2.51srm.com:9901/eureka
