server:
  port: 9900
eureka:
  instance:
    #映射本地hosts，模拟两台机器
    hostname: learn1.51srm.com
  client:
    #声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: false
    #是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://learn2.51srm.com:9901/eureka/
spring:
  application:
    name: eurka-service
#  security:
#    user:
#      name: admin
#      password: admin
