server:
  port: 8761
eureka:
  instance:
    #映射本地hosts，模拟两台机器
    hostname: learn1.51srm.com
  client:
    #声明是否将自己的信息注册到 Eureka 服务器上
    registerWithEureka: false
    #是否到 Eureka 服务器中抓取注册信息
    fetchRegistry: false
    serviceUrl:
      #配合eureka2工程做集群注册中心
#      defaultZone: http://learn2.51srm.com:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
  server:
    #自我保护机制 默认true 生产建议true
    enable-self-preservation: false
spring:
  application:
    name: eurka-service
#  security:
#    user:
#      name: admin
#      password: admin
