server:
  port: 8012
spring:
  application:
    name: order-hystrix-service

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    #是否从Eureka服务端抓取已有的注册信息，集群情况下需设置为true配合ribbon做负载
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

#设置OpenFeign客户端的超时时间
ribbon:
  #建立连接超时时间
  ReadTimeout: 5000
  #建立连接后访问服务超时时间
  ConnectTimeout: 5000


logging:
  level:
    com.liuwei.learn.hystrix.service.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true