server:
  port: 8021
  servlet:
    context-path: /api/v1

spring:
  application:
    name: payment-hystrix-service
  #  security:
  #    user:
  #      name: admin
  #      password: admin

swagger:
  enabled: true

eureka:
  instance:
    hostname: localhost
    #eureka 主机名称
    #    instance-id: 51srm
    prefer-ip-address: true #访问路径可以显示ip
  client:
    registerWithEureka: true
    #是否从Eureka服务端抓取已有的注册信息，集群情况下需设置为true配合ribbon做负载
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9900/eureka
