spring:
  application:
    name: user-service
server:
  port: 8030

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
springfox:
  documentation:
    swagger-ui:
      enabled: true
